# Generated by Django 5.0.2 on 2024-03-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
        migrations.AddField(
            model_name='image',
            name='is_profile_picture',
            field=models.BooleanField(default=False),
        ),
    ]
